
// Objective-C API for talking to the following Go packages
//
//	blink.com/quicproxy/bailingquic
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Bailingquic_FRAMEWORK_H__
#define __Bailingquic_FRAMEWORK_H__

#include "Bailingquic.objc.h"
#include "Universe.objc.h"

#endif
