# Uncomment the next line to define a global platform for your project
platform :ios, '7.0'

target 'SealTalk' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod "RedpacketLib"
  # Pods for SealTalk

end

target 'SealTalk copy' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod "RedpacketAliAuthLib"
  # Pods for SealTalk copy

end

